(defun back-to-indentation-or-beginning ()
   (interactive)
   (if (and (looking-back "^\s+")
           (eq last-command 'back-to-indentation-or-beginning))
       (beginning-of-line)
     (back-to-indentation)))
